Repository dogo-dogo/backend, pull requests merged in 2023-10, with the labels that each got.

#17 Refactor #13 delete controller
  src/main/java/com/example/tooktook/controller/QuestionController.java
  src/main/java/com/example/tooktook/controller/httpTestController.java
  src/main/java/com/example/tooktook/model/dto/MemberDto.java
  src/main/java/com/example/tooktook/model/dto/Neo4Dto.java
  src/main/java/com/example/tooktook/model/dto/QuestionDTO.java
  src/main/java/com/example/tooktook/model/entity/Member.java
  src/main/java/com/example/tooktook/service/KakaoService.java
  src/main/java/com/example/tooktook/service/Neo4jService.java
  src/main/resources/application-local.properties
  src/main/resources/application-prod.properties
Labels: fix

#23 Feat 22 enum create
  .github/workflows/gradle.yml
  pull_request_template.md
  src/main/java/com/example/tooktook/component/jwt/JwtTokenProvider.java
  src/main/java/com/example/tooktook/component/jwt/RequestOAuthInfoService.java
  src/main/java/com/example/tooktook/component/security/AuthTokensGenerator.java
  src/main/java/com/example/tooktook/component/security/CurrentMember.java
  src/main/java/com/example/tooktook/config/SecurityConfig.java
  src/main/java/com/example/tooktook/controller/AuthController.java
  src/main/java/com/example/tooktook/controller/QuestionController.java
  src/main/java/com/example/tooktook/model/dto/MemberDto.java
  src/main/java/com/example/tooktook/model/dto/QuestionEnum.java
  src/main/java/com/example/tooktook/model/entity/Category.java
  src/main/java/com/example/tooktook/model/entity/Member.java
  src/main/java/com/example/tooktook/model/entity/Question.java
  src/main/java/com/example/tooktook/model/enumDto/Bye2023.java
  src/main/java/com/example/tooktook/model/enumDto/CategoryEnum.java
  src/main/java/com/example/tooktook/model/enumDto/Compliment.java
  src/main/java/com/example/tooktook/model/enumDto/Fi.java
  src/main/java/com/example/tooktook/model/enumDto/Growth.java
  src/main/java/com/example/tooktook/model/enumDto/Hello2024.java
  src/main/java/com/example/tooktook/service/Neo4jService.java
  src/main/resources/application-local.properties
  src/main/resources/application-prod.properties
Labels: feat

#25 Feat 24 answer node
  src/main/java/com/example/tooktook/component/security/AuthTokensGenerator.java
  src/main/java/com/example/tooktook/component/security/CurrentMember.java
  src/main/java/com/example/tooktook/controller/AuthController.java
  src/main/java/com/example/tooktook/controller/QuestionController.java
  src/main/java/com/example/tooktook/exception/ErrorCode.java
  src/main/java/com/example/tooktook/model/dto/CategoryDto.java
  src/main/java/com/example/tooktook/model/dto/CategoryListDto.java
  src/main/java/com/example/tooktook/model/dto/MemberDto.java
  src/main/java/com/example/tooktook/model/dto/Neo4Dto.java
  src/main/java/com/example/tooktook/model/dto/QuestionDTO.java
  src/main/java/com/example/tooktook/model/dto/QuestionDto.java
  src/main/java/com/example/tooktook/model/dto/QuestionEnum.java
  src/main/java/com/example/tooktook/model/entity/Category.java
  src/main/java/com/example/tooktook/model/entity/Member.java
  src/main/java/com/example/tooktook/model/entity/Question.java
  src/main/java/com/example/tooktook/model/enumDto/Bye2023.java
  src/main/java/com/example/tooktook/model/enumDto/CategoryEnum.java
  src/main/java/com/example/tooktook/model/enumDto/Compliment.java
  src/main/java/com/example/tooktook/model/enumDto/Fi.java
  src/main/java/com/example/tooktook/model/enumDto/Growth.java
  src/main/java/com/example/tooktook/model/enumDto/Hello2024.java
  src/main/java/com/example/tooktook/model/repository/CategoryNeo4jRepository.java
  src/main/java/com/example/tooktook/model/repository/MemberNeo4jRepository.java
  src/main/java/com/example/tooktook/model/repository/QuestionNeo4jRepository.java
  src/main/java/com/example/tooktook/service/Neo4jService.java
Labels: feat

#37 refactor : SecurityConfig filter 에러 흰페이지 나오는 BUG FIX
  src/main/java/com/example/tooktook/config/SecurityConfig.java
Labels: bug, fix

#38 Dev
  src/main/java/com/example/tooktook/common/response/ApiResponse.java
  src/main/java/com/example/tooktook/common/response/ResponseCode.java
  src/main/java/com/example/tooktook/common/response/ValidMember.java
  src/main/java/com/example/tooktook/component/jwt/JwtTokenFilter.java
  src/main/java/com/example/tooktook/component/jwt/JwtTokenProvider.java
  src/main/java/com/example/tooktook/component/security/AuthTokensGenerator.java
  src/main/java/com/example/tooktook/component/security/CurrentMember.java
  src/main/java/com/example/tooktook/component/security/LoginMember.java
  src/main/java/com/example/tooktook/config/SecurityConfig.java
  src/main/java/com/example/tooktook/config/SwaggerConfig.java
  src/main/java/com/example/tooktook/controller/AuthController.java
  src/main/java/com/example/tooktook/controller/MemberController.java
  src/main/java/com/example/tooktook/controller/QuestionController.java
  src/main/java/com/example/tooktook/exception/ExceptionControllerAdvice.java
  src/main/java/com/example/tooktook/exception/GlobalException.java
  src/main/java/com/example/tooktook/model/dto/enumDto/Bye2023.java
  src/main/java/com/example/tooktook/model/dto/enumDto/CategoryEnum.java
  src/main/java/com/example/tooktook/model/dto/enumDto/Compliment.java
  src/main/java/com/example/tooktook/model/dto/enumDto/Fi.java
  src/main/java/com/example/tooktook/model/dto/enumDto/Growth.java
  src/main/java/com/example/tooktook/model/dto/enumDto/Hello2024.java
  src/main/java/com/example/tooktook/model/dto/enumDto/MemberRole.java
  src/main/java/com/example/tooktook/model/dto/memberDto/MemberDetailsDto.java
  src/main/java/com/example/tooktook/model/entity/BaseTimeEntity.java
  src/main/java/com/example/tooktook/model/entity/Member.java
  src/main/java/com/example/tooktook/model/entity/Question.java
  src/main/java/com/example/tooktook/model/repository/AnswerNeo4jRepository.java
  src/main/java/com/example/tooktook/service/KakaoService.java
  src/main/java/com/example/tooktook/service/MemberService.java
  src/main/java/com/example/tooktook/service/Neo4jService.java
  src/main/resources/application-local.properties
  src/main/resources/application-prod.properties
Labels: feat

#41 feat : 알람 기능 구현
  src/main/java/com/example/tooktook/common/response/ValidMember.java
  src/main/java/com/example/tooktook/component/jwt/JwtTokenFilter.java
  src/main/java/com/example/tooktook/controller/AnswerController.java
  src/main/java/com/example/tooktook/controller/MemberController.java
  src/main/java/com/example/tooktook/exception/ErrorCode.java
  src/main/java/com/example/tooktook/model/entity/Member.java
  src/main/java/com/example/tooktook/model/entity/Notification.java
  src/main/java/com/example/tooktook/model/repository/AnswerNeo4jRepository.java
  src/main/java/com/example/tooktook/model/repository/NotificationRepository.java
  src/main/java/com/example/tooktook/service/AnswerService.java
  src/main/java/com/example/tooktook/service/MemberService.java
  src/main/java/com/example/tooktook/service/Neo4jService.java
Labels: feat
